import type { EmergencyContact } from "../types";

/**
 * Foruddefinerede, tidligere verificerede nødkontakter (fra Fase 0-
 * specifikationen). Redigerbare i administration - denne fil er kun
 * saaet/startdata, ikke den levende kilde (den ligger i IndexedDB).
 */
export const SEED_CONTACTS: EmergencyContact[] = [
  {
    id: "jrcc-groenland",
    name: "JRCC Greenland - maritim og luft-SAR",
    phone: "+299 36 40 10",
    region: "groenland",
    domain: "generel",
    authority: "Joint Rescue Coordination Centre Groenland",
    source: "Fase 0-specifikation",
    lastVerified: "2026-05-01",
    active: true,
  },
  {
    id: "alarm-112-gl",
    name: "Akut alarm",
    phone: "112",
    region: "groenland",
    domain: "generel",
    authority: "Alarmcentral",
    source: "Fase 0-specifikation",
    lastVerified: "2026-05-01",
    active: true,
  },
  {
    id: "politi-groenland",
    name: "Groenlands Politi, ikke akut",
    phone: "+299 70 14 48",
    region: "groenland",
    domain: "land",
    authority: "Groenlands Politi",
    source: "Fase 0-specifikation",
    lastVerified: "2026-05-01",
    active: true,
  },
  {
    id: "fic-soendrestroem",
    name: "FIC Soendrestroem",
    phone: "+299 36 33 18",
    region: "groenland",
    domain: "luft",
    authority: "Flight Information Centre",
    source: "Fase 0-specifikation",
    lastVerified: "2026-05-01",
    active: true,
  },
  {
    id: "mrcc-torshavn",
    name: "MRCC Torshavn",
    phone: "+298 35 13 00",
    region: "faeroeerne",
    domain: "maritim",
    authority: "Maritime Rescue Coordination Centre Torshavn",
    source: "Fase 0-specifikation",
    lastVerified: "2026-05-01",
    active: true,
  },
  {
    id: "alarm-112-fo",
    name: "Akut alarm",
    phone: "112",
    region: "faeroeerne",
    domain: "generel",
    authority: "Alarmcentral",
    source: "Fase 0-specifikation",
    lastVerified: "2026-05-01",
    active: true,
  },
  {
    id: "politi-foeroeerne",
    name: "Politi, ikke akut",
    phone: "114",
    region: "faeroeerne",
    domain: "land",
    authority: "Foeroeya Politi",
    source: "Fase 0-specifikation",
    lastVerified: "2026-05-01",
    active: true,
  },
  {
    id: "jrcc-danmark",
    name: "JRCC Danmark",
    phone: "+45 89 43 30 99",
    region: "danmark",
    domain: "generel",
    authority: "Joint Rescue Coordination Centre Danmark",
    source: "Fase 0-specifikation",
    lastVerified: "2026-05-01",
    active: true,
  },
];
